name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
  
  # build:
  #   name: dev.51bmsh.com 测试
  #   runs-on: ubuntu-latest
  #   steps:
  #     # 切换分支
  #     - name: Checkout
  #       uses: actions/checkout@master
  #     # 下载 git submodule
  #     - uses: srt32/git-actions@v0.0.3
  #       with:
  #         args: git submodule update --init --recursive
  #     # 使用 node:10
  #     - name: use Node.js 10
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     # npm install
  #     - name: npm install and build
  #       run: |
  #         npm install
  #         npm run build
  #       env:
  #         CI: true
  #     # Deploy
  #     - name: 部署服务器
  #       uses: easingthemes/ssh-deploy@v2.0.7
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.mac_Token }}
  #         ARGS: "-avzr --delete"
  #         SOURCE: "build/"
  #         REMOTE_HOST: "161.117.88.12"
  #         REMOTE_USER: "root"
  #         REMOTE_PORT: "20002"
  #         TARGET: "/jianbing/base/h5/pages/gitActions/homePage"